// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlWK8hNBSjT0tCgkr2lmr7J_S3yb-z2Yk',
    appId: '1:648575809488:web:2a6a464c44ee665e13abd5',
    messagingSenderId: '648575809488',
    projectId: 'accel-attendance-d3d44',
    authDomain: 'accel-attendance-d3d44.firebaseapp.com',
    storageBucket: 'accel-attendance-d3d44.firebasestorage.app',
    measurementId: 'G-DWEVRXDJSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZOPQoGZMP52RnYhd57frKgk9u6HHjGks',
    appId: '1:648575809488:android:97f41587ca00f9e413abd5',
    messagingSenderId: '648575809488',
    projectId: 'accel-attendance-d3d44',
    storageBucket: 'accel-attendance-d3d44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhUsl08zseZJIRRTrU8VJVY4SkYsC4r38',
    appId: '1:648575809488:ios:a3bf55670aa0104713abd5',
    messagingSenderId: '648575809488',
    projectId: 'accel-attendance-d3d44',
    storageBucket: 'accel-attendance-d3d44.firebasestorage.app',
    iosClientId: '648575809488-5goassfnbqp99jushcpdvehctkoft6oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.fieldAccel',
  );
}
